services:
  postgres:
    image: postgres:ru_RU.utf8
    build: ./Postgres
    ports:
      - "5432"
    restart: always
    volumes:
      - chatbot:/app/Database/pgdata
    environment:
      POSTGRES_USER: NSTUChatbot
      POSTGRES_PASSWORD: NSTUChatbot
      POSTGRES_DB: NSTUChatbotDatabase
      PGDATA: /app/Database/pgdata

  chatbotapi:
    image: chatbotapi:latest
    environment:
      migrateOnStartup: "true"
    build: ./Database
    ports:
      - 5004:8000

  train_nlu:
    image: diploma_rasa_project
    build: ./NLU
    volumes:
      - chatbot:/app/NLU/data
      - chatbot:/app/NLU/models
    command: train nlu

  run_nlu:
    image: diploma_rasa_project
    build: ./NLU
    volumes:
      - chatbot:/app/NLU/data
      - chatbot:/app/NLU/models
    ports:
      - 5005:5005
    command: run --enable-api

volumes:
  chatbot:
