services:
    train:
      image: diploma_rasa_project
      build: ./NLU
      volumes:
        - chatbot:/app/data
        - chatbot:/app/models
      command: train nlu
    
    run:
      image: diploma_rasa_project
      build: ./NLU
      volumes:
        - chatbot:/app/data
        - chatbot:/app/models
      ports:
        - "8080:5005"
      command: run --enable-api

volumes:
    chatbot:
