services:
  postgres:
    image: postgres:ru_RU.utf8
    build: ./Postgres
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: NSTUChatbot
      POSTGRES_PASSWORD: NSTUChatbot
      POSTGRES_DB: NSTUChatbotDatabase

  chatbotapi:
    image: chatbotapi:latest
    environment:
      migrateOnStartup: "true"
    depends_on:
      - postgres
    build: ./Database
    ports:
      - 5004:8000

  nlu:
    image: diploma_rasa_project
    build: ./NLU
    volumes:
      - nlu:/app/NLU/models
    ports:
      - 5005:5005

volumes:
  nlu:
